### ISSUE TITLE
Maui shell weird scaling issue

### ISSUE THREAD

**Issue by ubl8** [Nitrux/maui-shell#37] opened 2022-05-20 13:45 UTC
**Describe the bug**
When trying to scale the screen in Maui shell all scales well except for the windows from the applications. They scale the opposite.

**To Reproduce**
launch maui-shell with following command:
```
env QT_QPA_PLATFORM=wayland QT_SCALE_FACTOR=3 QT_SCREEN_SCALE_FACTORS=1 QT_AUTO_SCREEN_SCALE_FACTOR=0 /usr/bin/startcask-wayland
```

**Expected behavior**
The window should stay fullscreen and not scale down

**Screenshots**
Picture 1 is with QT_SCALE_FACTOR=1
Picture 2 is with QT_SCALE_FACTOR=3

![photo_2022-05-20_15-40-02](https://user-images.githubusercontent.com/28589031/169541102-5b81dd20-778e-43ff-8a7a-cbf448094f4e.jpg)

![photo_2022-05-20_15-44-23](https://user-images.githubusercontent.com/28589031/169541173-6ea5c3dc-06b0-4c0e-b425-d3d1ecb4f349.jpg)

**Desktop (please complete the following information):**
 - OS: maui-shell on postmarketOS
 - Version postmarketOS: edge, maui-shell: 2.1.2

**Comment by UriHerrera** [comment] 2022-05-20 20:22
Posible duplicate of  [Overscaled apps #8](https://github.com/Nitrux/maui-shell/issues/8).

**Comment by ubl8** [comment] 2022-05-20 20:55
could be a doublicate but the look seems to be the opposite. 

The scaling of the content seems fine but the window it self is shrinking.

**Comment by milohr** [comment] 2022-07-15 15:42
fixed. scaling can be set via MauiManServer dbus Screen object.

**Closed by milohr** 2022-07-15 15:42 UTC
Labels: duplicate
