### ISSUE TITLE
Wrong orientation on desktop

### ISSUE THREAD

**Issue by newyorkthink** [Nitrux/maui-shell#48] opened 2023-01-16 14:24 UTC
i3wm run it , wromg oriemtation

![image](https://user-images.githubusercontent.com/87791643/212700604-b193cbde-b0c8-41dd-bf48-5e26e099e9a3.png)

**Comment by UriHerrera** [comment] 2023-01-16 19:15
Duplicate of #45

**Closed by UriHerrera** 2023-01-16 19:15 UTC
